# Generated by Django 4.0.4 on 2022-06-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=3)),
                ('after', models.CharField(max_length=100, null=True)),
                ('pronunciation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=3)),
                ('after', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100, null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sentence')),
            ],
        ),
    ]
